const express = require('express');
const router = express.Router();

const words = [
        'druxy',
        'swipple',
        'phoniatrics',
        'pundonor',
        'metapolitics',
        'naupegical',
        'yewen',
        'pornotopia',
        'midinette',
        'saki',
        'dageraad',
        'spathodea',
        'palaeogeography',
        'osteophyte',
        'skald',
        'palladian',
        'phalarope',
        'pnyx',
        'moria',
        'stereoscope',
        'vinification',
        'chancel',
        'nieve',
        'flumen',
        'galbanum',
        'volitant',
        'sightworthy',
        'anacardic',
        'epanalepsis',
        'weld',
        'hylarchic',
        'cathedra',
        'exsanguinous',
        'nonobstant',
        'homoeoptoton',
        'pam',
        'jussive',
        'pedagoguery',
        'incarnadine',
        'puniceous',
        'nutrice',
        'archimandrite',
        'reticello',
        'raisonneur',
        'scruto',
        'malison',
        'wheaten',
        'adaxial',
        'natatorium',
        'epistatic',
        'perseity',
        'carnassial',
        'foudroyant',
        'achromatopsia',
        'chthonophagia',
        'crachoir',
        'thalassotherapy',
        'mental',
        'diachoretic',
        'myristicivorous',
        'largition',
        'flagellantism',
        'iliac',
        'salvo',
        'tellurian',
        'hérissé',
        'tocsin',
        'somnipathy',
        'nankeen',
        'hyperanarchy',
        'pight',
        'prisoptometer',
        'paroemiographer',
        'porriginous',
        'physiocracy',
        'conative',
        'assoil',
        'dactyloid',
        'accubation',
        'circumaviate',
        'spinnaker',
        'diffugient',
        'pelology',
        'queach',
        'prolate',
        'guttatim',
        'adelphogamy',
        'tachyscope',
        'gossypine',
        'refugium',
        'formic',
        'empasm',
        'biolith',
        'winterbourne',
        'porogamy',
        'roband',
        'tacheometer',
        'violone',
        'yrneh',
        'bodge',
        'anotic',
        'hipped',
        'necromania',
        'métayage',
        'nephrography',
        'spirketting',
        'torpor',
        'latinitaster',
        'silage',
        'sympatric',
        'mediagenic',
        'hesternal',
        'imbricate',
        'tambour',
        'thymogenic',
        'incept',
        'becket',
        'prothonotary',
        'glaireous',
        'abyssopelagic',
        'charpie',
        'echopraxia',
        'canescent',
        'materialism',
        'orphrey',
        'anthomania',
        'lactiferous',
        'trochlear',
        'dehors',
        'innominate',
        'coacervate',
        'futurition',
        'sanies',
        'afterdeck',
        'angiography',
        'alembicated',
        'zoophobia',
        'cantle',
        'rubiginous',
        'quotennial',
        'whitlow',
        'quipu',
        'dysania',
        'shopocracy',
        'grufted',
        'stelliferous',
        'cubation',
        'comiphorous',
        'capstan',
        'hirudinean',
    ]

router.get('/', (req, res) => {
    res.json(words);
});

router.get('/:count', (req, res) => {
    let count = parseInt(req.params.count);
    if(!count || count < 0) return res.status(400).json({ message: 'Invalid number of words'});
    res.json(shuffle(words).splice(0, count));
});

const shuffle = (array) => {
  let currentIndex = array.length,  randomIndex;
  while (currentIndex != 0) {
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;
    [array[currentIndex], array[randomIndex]] = [
      array[randomIndex], array[currentIndex]];
  }
  return array;
}

module.exports = router;